from .adv_smooth import smooth_adversarial_perturbation
from .api import PerturbationConfig, apply_perturbation
from .evaluation import (
    AttackResult,
    binarize_predictions,
    compute_global_metrics,
    compute_targeted_success,
    compute_untargeted_asr,
    load_all_vulnerability_results,
    load_noise_vulnerability_results,
    predict_proba_batch,
    predict_proba_single,
    results_to_dataframe,
    run_attack_on_sample,
    run_noise_vulnerability_experiment,
    summarize_norms,
    summarize_smoothness,
    save_noise_vulnerability_results,
)
from .morphology import detect_r_peaks, local_amplitude_scaling, local_time_warp
from .noise import band_limited_noise, baseline_wander
from visualization import (
    plot_asr_time_class_heatmap,
    plot_asr_vs_strength,
    plot_asr_vs_time,
    plot_classwise_metric_bars,
    plot_norm_distributions,
    plot_overlay_with_diff,
    plot_robust_fraction_by_class,
    plot_strength_boxplot_by_class,
    plot_strength_histogram,
    plot_triptych,
)

__all__ = [
    "PerturbationConfig",
    "apply_perturbation",
    "baseline_wander",
    "band_limited_noise",
    "local_amplitude_scaling",
    "local_time_warp",
    "detect_r_peaks",
    "smooth_adversarial_perturbation",
    "AttackResult",
    "predict_proba_single",
    "predict_proba_batch",
    "binarize_predictions",
    "run_attack_on_sample",
    "results_to_dataframe",
    "summarize_norms",
    "summarize_smoothness",
    "compute_untargeted_asr",
    "compute_targeted_success",
    "compute_global_metrics",
    "run_noise_vulnerability_experiment",
    "save_noise_vulnerability_results",
    "load_noise_vulnerability_results",
    "load_all_vulnerability_results",
    "plot_triptych",
    "plot_overlay_with_diff",
    "plot_asr_vs_strength",
    "plot_asr_vs_time",
    "plot_asr_time_class_heatmap",
    "plot_norm_distributions",
    "plot_classwise_metric_bars",
    "plot_strength_histogram",
    "plot_strength_boxplot_by_class",
    "plot_robust_fraction_by_class",
]
